import type { GrubXProviderId } from "@/types/grubx";

export type ThemeMode = "cinematic-dark" | "amoled";
export type GrubXThemeMode = "dark" | "light";
export type BlurStrength = "soft" | "balanced" | "intense";
export type CardDensity = "comfortable" | "compact";
export type PosterQuality = "balanced" | "high" | "data-saver";
export type AudioProfile = "cinema" | "dialog" | "night";
export type AccentTone = "ember" | "electric" | "aurora";
export type PopupBlockerStrictness = "low" | "medium" | "high";
export type EmbedQualityMode = "auto" | "data-saver" | "high";
export type PlaybackMode = "direct" | "proxy" | "auto";
export type YouTubeSafeSearch = "strict" | "moderate" | "off";
export type SpotifyEmbedSize = "compact" | "large";
export type NavStyle = "floating" | "top-bar" | "compact";
export type MobileNavStyle = "bottom-bar" | "drawer";
export type AiOpenMode = "same-tab" | "new-tab";

export type FeatureToggles = {
  movies: boolean;
  tv: boolean;
  live: boolean;
  youtube: boolean;
  spotify: boolean;
  tiktok: boolean;
  search: boolean;
  watchlist: boolean;
  continueWatching: boolean;
  aiServer: boolean;
  providerReports: boolean;
  feedbackContact: boolean;
  safetyLegalPages: boolean;
  proxyPlayback: boolean;
  thirdPartyPlayback: boolean;
  tvModeScreenMirroring: boolean;
};

export type CustomProviderSettings = {
  id: string;
  name: string;
  baseUrl: string;
  embedUrlPattern: string;
  enabled: boolean;
  supportsMovie: boolean;
  supportsTv: boolean;
};

export type Settings = {
  featureToggles: FeatureToggles;
  safeMode: boolean;
  popupBlockerStrictness: PopupBlockerStrictness;
  recommendationsEnabled: boolean;
  embedQualityMode: EmbedQualityMode;
  playbackMode: PlaybackMode;
  enableServerSwitcher: boolean;
  showPlaybackWarnings: boolean;
  youtubeSafeSearch: YouTubeSafeSearch;
  youtubeResultCount: 8 | 12 | 20;
  spotifyEmbedSize: SpotifyEmbedSize;
  navStyle: NavStyle;
  mobileNavStyle: MobileNavStyle;
  aiOpenMode: AiOpenMode;
  showBuildInfo: boolean;
  showUpdateStatus: boolean;
  providerSettings: Record<string, boolean>;
  customProviders: CustomProviderSettings[];
  autoplayTrailers: boolean;
  theaterModeDefault: boolean;
  resumePlayback: boolean;
  rememberLastEpisode: boolean;
  autoplayNextEpisode: boolean;
  inlineTrailerMuted: boolean;
  showPlaybackTips: boolean;
  blockPopups: boolean;
  avoidLimitedProtectionServers: boolean;
  allowLimitedProtectionProviders: boolean;
  autoplayPlayback: boolean;
  defaultProvider: GrubXProviderId;
  uiTheme: GrubXThemeMode;
  compactMode: boolean;
  historyEnabled: boolean;
  trackingEnabled: boolean;
  enableAnimations: boolean;
  amoledMode: boolean;
  accentGlow: boolean;
  largeText: boolean;
  showRatings: boolean;
  showReleaseYear: boolean;
  cardDensity: CardDensity;
  blurStrength: BlurStrength;
  showClock24h: boolean;
  liveClock: boolean;
  dataSaver: boolean;
  reduceBackdropUsage: boolean;
  lowBandwidthMode: boolean;
  offlineCaching: boolean;
  prefetchRoutes: boolean;
  lazyLoadRows: boolean;
  posterQuality: PosterQuality;
  liveAutoRefresh: boolean;
  autoFocusSearch: boolean;
  rememberSearchFilters: boolean;
  showContinueWatching: boolean;
  showWatchlist: boolean;
  showTrendingOn404: boolean;
  audioProfile: AudioProfile;
  accentTone: AccentTone;
};
